[package]
name = "q_learning"
version = "0.1.0"
authors = ["shintaro"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
    rand = "0.7.0"
    serde = "1.0.99"
    serde_derive = "1.0.99"